set :domain, "10.10.0.141"
set :port, 9898
set :deploy_to, "/home/deploy/justice_time_mockup"
set :repository, "git@github.com:leonciocaminha/justice_time_mockup.git"
set :branch, "master"
set :user, "deploy"
set :rails_env, "production"
set :term_mode,     nil
set :rvm_path, "/usr/local/rvm/bin/rvm"
